version: "3.9"
services:
  postgres:
    build:
      context: ./postgres-db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - docker-compose.env

  keycloak:
    build:
      context: ../pep-keycloak
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - docker-compose.env
    depends_on:
      - postgres

  sonarqube:
    build:
      context: ./sonarqube
      dockerfile: Dockerfile
    user: sonarqube
    env_file:
      - docker-compose.env
    ports:
      - "19000:9000"
      - "19001:9001"
    depends_on:
      - postgres
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
